# Generated by Django 4.0.4 on 2022-06-06 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_variations_variation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variation',
            new_name='Variations',
        ),
    ]
